### ISSUE TITLE
Only limit if requested is not cached

### ISSUE THREAD

**Issue by liebig** [JWCook/requests-ratelimiter#76]
I am trying to implement a rate limiting with additional cache. This works as far as it goes, but I want to limit the rate only if the entry cannot be loaded from the cache. What is the best way to implement this?

```java
self.session = CachedLimiterSession(
            limiter=Limiter(RequestRate(2, Duration.SECOND * 5)),  # max 2 requests per 5 seconds
            bucket_class=SQLiteBucket,
            backend=SQLiteCache(ROOT_DIR + "/cache/cache.sqlite"),
        )
```

**Comment by JWCook** [comment]
Good news: if you're using the [example from the readme](https://github.com/JWCook/requests-ratelimiter#custom-session-example-requests-cache), then it will already behave as you've described.

This is due to cooperative multiple inheritance. `requests_cache.CacheMixin` is the first class in the list, so when there is a cache hit, it does not need to make a real request (which would call `requests_ratelimiter.LimiterMixin` and then `requests.Session`).

**Comment by liebig** [comment]
Thanks for the feedback. I used the sample code from the readme but unfortunately, despite caching, only 2 requests are made per 5 seconds.

```python
class CachedLimiterSession(CacheMixin, LimiterMixin, Session):
    """Session class with caching and rate-limiting behavior. Accepts arguments for both
    LimiterSession and CachedSession.
    """

class Api:
    def __init__(self):
        self.session = CachedLimiterSession(
            limiter=Limiter(RequestRate(2, Duration.SECOND * 5)),  # max 2 requests per 5 seconds
            bucket_class=SQLiteBucket,
            backend=SQLiteCache(ROOT_DIR + "/cache/cache.sqlite"),
        )

        self.action_session = CachedLimiterSession(
            limiter=Limiter(RequestRate(2, Duration.SECOND * 5)),  # max 2 requests per 5 seconds
            bucket_class=SQLiteBucket,
            backend=SQLiteCache(ROOT_DIR + "/cache/action.sqlite"),
            expire_after=604800  # 7 days
        )
...
```
