### ISSUE TITLE
Less than 1 `per_second` value doesn't work as expected

### ISSUE THREAD

**Issue by aaaaahaaaaa** [JWCook/requests-ratelimiter#84]
I would expect the following value `per_second=0.1` to limit to 1 request every 10 seconds. However it seems to fallback to 1 per second.

**Comment by JWCook** [comment]
Thanks for the bug report. I'll try to get that fixed.

Meanwhile, here's a slightly more verbose workaround you can use to get 1 request per 10 seconds:
```py
from pyrate_limiter import Duration, RequestRate, Limiter
from requests_ratelimiter import LimiterSession

limiter = Limiter(RequestRate(1, Duration.SECOND * 10))
session = LimiterSession(limiter=limiter)
```

**Comment by JWCook** [comment]
Float values now work as expected in v0.5!

Probably not important, but leaving this here for reference:

Internally these will get converted to a fraction (integer limit and interval), since the underlying algorithm only works with integers. If needed you can enable debug logs to verify that, for example:
```py
from logging import basicConfig
from requests_ratelimiter import LimiterSession

basicConfig(level='DEBUG')
session = LimiterSession(per_second=0.2, per_minute=20.5)
```
log:
```py
DEBUG:requests_ratelimiter.requests_ratelimiter:Creating Limiter with rates:
1/5s
41/120s
```
